// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cperikyhubaoljajphpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZXJpa3lodWJhb2xqYWpwaHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzgzNDMsImV4cCI6MjA2NjQ1NDM0M30.H0Ly-_IQs35WTRTT8-D1ejZxTdvJjZ84I2llxK3WdFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);